### ISSUE TITLE
Advanced configuration option aren't displayed if advanced options are not selected

### ISSUE THREAD

**Issue by Pewillia** [fgpv-vpgf/fgpa-apgf#344]

**Comment by jolevesq** [comment]
This is the expected behaviour

**Comment by ChrisLatRNCan** [comment]
This is the expected behaviour we don't want the user to be confused. The advance parameters are shown in italic if Advance is checked. For the validation part there's a twist. The form is validated not the model, so if you check Advance box insert an error on a mandatory field in an advance parameter then uncheck the box and then validate you won't see an error in the validation tree.

**Comment by ChrisLatRNCan** [comment]
Check for tileSchema validation in Basemaps.
