### ISSUE TITLE
Set up demo repo

### ISSUE THREAD

**Issue by yblain** [fgpv-vpgf/fgpa-apgf#4]
Can we use ECCC's cloud infrastructure currently used for the viewer?

**Comment by jolevesq** [comment]
I sent a message to @mweech about using the same infrastructure and he will get back to me. He agree it should be a good but he need to check if they have enough credit.

**Comment by jolevesq** [comment]
We will deploy or project on our server in SSC. We will talk with Paul Huppe about how to get access to it.

**Comment by yblain** [comment]
We need to follow-up with Paul to make sure we can deploy in the PAZ.

**Comment by jolevesq** [comment]
To make it easy to deploy and have live version of the application to test we will use what's have been done in #41 with the rv-main on https server.

**Comment by jolevesq** [comment]
It is still a problem. Every call must be on https. So the call to geogratis for geosearch or to our mapserver for basemap failed because it is not on https. The only way to avoid this is to have a custom domaine name.

The other thing is to use the version on github to create the config file then use the config file inside what @bchagnon created to link a configuration file inside the viewer easily with a parameter

**Comment by jolevesq** [comment]
So to test internally we can use the github gh-pages and use our layers on our https mapserver. We will need a working deployement to create real config file and to test custom layer.
